name: Next.js CI

on:
  push:
    branches: [dev]          
    paths:
      - "packages/nextjs/**"
      - ".github/workflows/**"
  pull_request:
    branches: [dev]          
    paths:
      - "packages/nextjs/**"
      - ".github/workflows/**"


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: 🧪 Run Vitest
        run: yarn test
        working-directory: ./packages/nextjs
      - name: 🔍 Run ESLint
        run: yarn lint
        working-directory: ./packages/nextjs

      - name: 🎨 Format Check
        run: yarn format:check
        working-directory: ./packages/nextjs

      - name: 🔡 Type Check
        run: yarn check-types
        working-directory: ./packages/nextjs

      - name: 🏗️ Build App
        run: yarn build
        working-directory: ./packages/nextjs
